---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux
spec:
  hostnames:
    - flux.youmans.io
  parentRefs:
    - name: envoy-internal
      namespace: networking
  rules:
    - backendRefs:
        - name: flux-operator
          namespace: flux-system
          port: 9080
