---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: youmans-io
spec:
  dnsNames:
    - youmans.io
    - "*.youmans.io"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: youmans-io-tls
  usages:
    - digital signature
